apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lb
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: lb
  hostPath:
    path: /mnt/pv-data/lb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node
          operator: In
          values:
          - master    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lb
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: lb 