apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-slave
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-slave
  hostPath:
    path: /mnt/pv-data/redis-slave
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-slave
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: redis-slave 