apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-sentinel
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis-sentinel
  hostPath:
    path: /mnt/pv-data/redis-sentinel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-sentinel
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: redis-sentinel 