apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
spec:
  selector:
    app: redis-sentinel
  type: ClusterIP
  ports:
  - name: p1
    port: 26379
    targetPort: 26379
  - name: p2
    port: 6379
    targetPort: 6379
