apiVersion: v1
data:
  haproxy.cfg: |
    resolvers mydns
        nameserver dns1 10.96.0.10:53
        accepted_payload_size 8192 # allow larger DNS payloads
    global
        maxconn 50000
        user haproxy
        group haproxy

    defaults
        timeout connect 10s
        timeout client 30s
        timeout server 30s
        log global
        maxconn 3000
    
    frontend http
        bind :8080

        default_backend stats

    backend stats
        mode http
        stats enable

        stats enable
        stats uri    /
        stats refresh 1s
        stats show-legends
        stats admin if TRUE

    frontend db-master
        bind *:5432
        default_backend db-master-backend

    backend db-master-backend
        balance roundrobin
        server server1 postgres-0.psg-primary.default.svc.cluster.local:5432 resolvers mydns init-addr none

    frontend db-replica
        bind *:5433
        default_backend db-replica-backend

    backend db-replica-backend
        balance roundrobin
        server server1 postgres-replica-0.psg-replica.default.svc.cluster.local:5432 resolvers mydns init-addr none

    frontend redis-master
        bind *:6379
        default_backend redis-master-backend

    backend redis-master-backend
        mode tcp
        balance first
        option tcp-check
        
        tcp-check send AUTH\ 123\r\n
        tcp-check send info\ replication\r\n
        tcp-check expect string role:master

        server master redis-0.redis-master.default.svc.cluster.local:6379 maxconn 1024 check inter 1s resolvers mydns init-addr none
        server server2 redis-slave-0.redis-slave.default.svc.cluster.local:6379 maxconn 1024 check inter 1s resolvers mydns init-addr none

    frontend redis-slave
        bind *:6380
        default_backend redis-slave-backend

    backend redis-slave-backend
        mode tcp
        balance roundrobin
        option tcp-check

        tcp-check send AUTH\ 123\r\n
        tcp-check send info\ replication\r\n
        tcp-check expect string role:slave

        server master redis-0.redis-master.default.svc.cluster.local:6379 maxconn 1024 check inter 1s resolvers mydns init-addr none
        server server2 redis-slave-0.redis-slave.default.svc.cluster.local:6379 maxconn 1024 check inter 1s resolvers mydns init-addr none

kind: ConfigMap
metadata:
  name: haproxy-config
---
apiVersion: v1
data:
  redis.conf: |
    requirepass "123"
kind: ConfigMap
metadata:
  name: redis-master-config
---
apiVersion: v1
data:
  sentinel.conf: |
    sentinel auth-pass mymaster 123
    sentinel monitor mymaster 10.0.53.181 6379 2
    sentinel down-after-milliseconds mymaster 600
    sentinel failover-timeout mymaster 1800
kind: ConfigMap
metadata:
  name: redis-sentinel-config
---
apiVersion: v1
data:
  redis-slave.conf: |
    masterauth "123"
    replicaof redis-master 6379
kind: ConfigMap
metadata:
  name: redis-slave-config
